<?php use Phalcon\Tag; ?>
<div class="col-md-5 col-md-offset-1 an-item">
    <ul class="nav nav-tabs an-item-tab">
        <li class="active">
            <a href="#item-tab-image-<?= $item->id ?>" data-toggle="tab"><?= $item->name ?></a>
        </li>
        <li>
            <a href="#item-tab-info-<?= $item->id ?>" data-toggle="tab">Information</a>
        </li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane fade in active" id="item-tab-image-<?= $item->id ?>">
            <?= $item->imageView() ?>
        </div>
        <div class="tab-pane fade" id="item-tab-info-<?= $item->id ?>">
            <table class="table table-hover">
                <tr>
                    <th class="success"><?= $item->getAttributeLabel('name') ?></th>
                    <td><?= $item->name ?></td>
                </tr>
                <tr>
                    <th class="success"><?= $item->getAttributeLabel('price') ?></th>
                    <td><?= $item->price ?></td>
                </tr>
                <tr>
                    <th class="success"><?= $item->getAttributeLabel('type') ?></th>
                    <td><?= $item->type_value ?></td>
                </tr>
                <tr>
                    <th class="success"><?= $item->getAttributeLabel('status') ?></th>
                    <td><?= $item->status_value ?></td>
                </tr>
                <tr>
                    <th class="success"><?= $item->getAttributeLabel('description') ?></th>
                    <td><?= $item->description ?></td>
                </tr>
            </table>
        </div>
    </div>
</div>


