<?php
use Phalcon\Tag;
echo $this->getContent();
/**
 * @var ItemShops[] $item_shops
 */
?>
<h1><a href="<?= $this->url->get("shop/view/{$shop->id}"); ?>"><span class="item-name text-warning"><?= $shop->name ?></span></a>'s Items </h1>
<hr>

<table class="table table-striped table-hover">
    <thead>
    <tr>
        <th>Item</th>
        <th>Type</th>
        <th>Price</th>
        <th>Status</th>
        <th>Start Sale Date</th>
        <th>End Sale Date</th>
        <th>Created At</th>
        <th>Updated At</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
        <?php foreach($item_shops as $item_shop): ?>
        <?php
        /**
         * @var ItemUsers $item_user
         */
        ?>
            <tr class="<?= $item_shop->isOnSale() ? 'success' : '' ?>">
                <td><?= $item_shop->item->name ?></td>
                <td><?= $item_shop->item->getTypeValue() ?></td>
                <td><?= $item_shop->getSalePrice() ?></td>
                <td><?= $item_shop->printStatus() ?></td>
                <td><?= $item_shop->start_sale_date ?> </td>
                <td><?= $item_shop->end_sale_date ?> </td>
                <td><?= $item_shop->created_at ?> </td>
                <td><?= $item_shop->updated_at ?> </td>
                <td>
                    <div class="btn-group-xs">
                        <a href="<?= $this->url->get("itemshop/update/{$item_shop->id}"); ?>" class="btn btn-info btn-action" role="button">Edit</a>
                        <?= $item_shop->printActionButtonGroup() ?>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>