<?php use Phalcon\Tag;

/**
 * @var Users $current_user
 */
echo $this->getContent(); ?>

<div class="row">
    <div class="col-lg-4 col-xs-12">
        <?= $item->imageView() ?>
    </div>
    <div class="col-lg-8 col-xs-12">
        <table class="table table-hover">
            <tr>
                <th class="success"><?= $item->getAttributeLabel('name') ?></th>
                <td><?= $item->name ?>
                    <?= ViewHelper::likeButton($item, $favorite) ?>
                </td>
            </tr>
            <tr>
                <th class="success"><?= $item->getAttributeLabel('type') ?></th>
                <td>
                    <?= $item->getTypeValue() ?>
                    <br><span class="text-info"><?= $item->getItemTypeDescription() ?></span>
                </td>
            </tr>
            <tr>
                <th class="success"><?= $item->getAttributeLabel('status') ?></th>
                <td><?= $item->getStatusValue() ?></td>
            </tr>
            <tr>
                <th class="success">Sellers</th>
                <td><?php foreach($item->saleUsers as $seller) {
                        echo $seller->getViewLink() . "<br/>";
                    } ?></td>
            </tr>
            <tr>
                <th class="success">Shops</th>
                <td><?php foreach($item->saleShops as $shop) {
                        echo $shop->getViewLink() . "<br/>";
                    } ?></td>
            </tr>
            <tr>
                <th class="success"><?= $item->getAttributeLabel('description') ?></th>
                <td><?= $item->description ?></td>
            </tr>
            <tr>
                <th class="success"><?= $item->getAttributeLabel('created_by') ?></th>
                <td><?= $item->user->getUserDisplayName() ?></td>
            </tr>
            <tr>
                <th class="success"><?= $item->getAttributeLabel('approved_by') ?></th>
                <td><?= $item->approved_by ?></td>
            </tr>
            <tr>
                <th class="success"><?= $item->getAttributeLabel('created_at') ?></th>
                <td><?= $item->created_at ?></td>
            </tr>
            <tr>
                <th class="success"><?= $item->getAttributeLabel('updated_at') ?></th>
                <td><?= $item->updated_at ?></td>
            </tr>
            <tr>
                <th class="success">Action</th>
                <td>
                    <div class="btn-group-xs">
                        <?php if ($current_user->canEditItem($item)): ?>
                            <a href="<?= $this->url->get("item/update/{$item->id}")?>" class="btn btn-warning btn-action"><i class="fa fa-edit"></i> Edit </a>
                            <a href="<?= $this->url->get("item/invoices/{$item->id}")?>" class="btn btn-info btn-action"> View all invoices </a>
                        <?php endif; ?>
                        <?php if ($current_user->canCreateBuyItemRequest($item)): ?>
                            <button class='btn btn-primary btn-action item-sell-request' id="item-sell-request-<?= $item->id ?>" data-item-id='<?= $item->id ?>'>Request Sell This Item</button>
                        <?php endif; ?>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</div>
<hr>
<?php $num = count($invoices); ?>
<?php if($num): ?>
    <h3 class="text-primary">
        Total <?= $num ?> <?= $num > 1 ? 'Invoices' : 'Invoice' ?> today
    </h3>
    <?= $this->partial('invoice/_received_list', ['invoices' => $invoices]); ?>
<?php else: ?>
    <h3 class="text-warning">
        No invoice today
    </h3>
<?php endif; ?>
