<?php
/**
 * @var Users $current_user
 */
?>
<div class="panel panel-<?= $type == Requests::TYPE_SENT ? 'info' : 'warning' ?>">
    <!-- Default panel contents -->
    <div class="panel-heading"><?= $type == Requests::TYPE_SENT ? 'Sent' : 'Received' ?> Requests</div>

    <!-- Table -->
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <?php if ($type == Requests::TYPE_SENT): ?>
                <th>To user</th>
            <?php else: ?>
                <th>From user</th>
            <?php endif; ?>
            <th>Type</th>
            <th>Item</th>
            <th>Status</th>
            <th>Created At</th>
            <th>Updated At</th>
            <th>Updated By</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($requests as $request): ?>
            <?php
            /**
             * @var Requests $request
             */
            ?>

            <tr class="active">
                <?php if ($type == Requests::TYPE_SENT): ?>
                    <td><?= $request->getDestination() ?></td>
                <?php else: ?>
                    <td><?= $request->fromUser ? $request->fromUser->username : '' ?></td>
                <?php endif; ?>
                <td><?= $request->getTypeValue() ?></td>
                <td><?= $request->item ? $request->item->name : '' ?></td>
                <td><?= $request->printStatus() ?></td>
                <td><?= $request->created_at ?></td>
                <td><?= $request->updated_at ?></td>
                <td><?= $request->updatedBy ? $request->updatedBy->username : '' ?></td>
                <td>
                    <?php if($type == Requests::TYPE_SENT && $request->isStatusSent()): ?>
                        <button class="btn btn-danger btn-sm">Cancel</button>
                    <?php else: ?>
                        <button class="btn btn-primary btn-sm">Accept</button>
                        <button class="btn btn-danger btn-sm">Reject</button>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>


