<?php
/**
 * @var Users $current_user
 * @var Requests[] $requests
 * @var Pagination $pagination
 * @var string $type
 */
echo $this->getContent();
?>
<div class="panel panel-warning">
    <!-- Default panel contents -->
    <div class="panel-heading">
        Received Requests
            <?php if($type != 'all'): ?>
                <a href="<?= $this->url->get("request/receivedrequests/all"); ?>" class="btn btn-success btn-xs" role="button">All</a>
                <div class="btn-group-xs pull-right">
                    <a href="<?= $this->url->get("request/accept/all"); ?>" class="btn btn-primary btn-xs" role="button">Accept All</a>
                    <a href="<?= $this->url->get("request/reject/all"); ?>" class="btn btn-danger btn-xs" role="button">Reject All</a>
                </div>
            <?php else: ?>
            <a href="<?= $this->url->get("request/receivedrequests/restricted"); ?>" class="btn btn-success btn-xs" role="button">Only Sent</a>
        <?php endif; ?>
    </div>

    <!-- Table -->
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>From user</th>
            <th>From shop</th>
            <th>Item</th>
            <th>Type</th>
            <th>Status</th>
            <th>Created At</th>
            <th>Updated At</th>
            <th>Updated By</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($requests as $request): ?>
            <?php
            /**
             * @var Invoices $request
             */
            ?>

            <tr class="active">
                <td><?= $request->fromUser ? $request->fromUser->username : '' ?></td>
                <td><?= $request->shop ? $request->shop->name : '' ?></td>
                <td><?= $request->item ? $request->item->name : '' ?></td>
                <td><?= $request->getTypeValue() ?></td>
                <td><?= $request->printStatus() ?></td>
                <td><?= $request->created_at ?></td>
                <td><?= $request->updated_at ?></td>
                <td><?= $request->updatedBy ? $request->updatedBy->username : ''  ?></td>
                <td>
                    <?php if($request->isStatusSent()): ?>
                        <a href="<?= $this->url->get("request/accept/{$request->id}"); ?>" class="btn btn-primary btn-xs btn-action" role="button">Accept</a>
                        <a href="<?= $this->url->get("request/reject/{$request->id}"); ?>" class="btn btn-danger btn-xs btn-action" role="button">Reject</a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?= $pagination->generatePagination() ?>