<?php
/**
 * @var Users $current_user
 */
echo $this->getContent();
?>
<div class="panel panel-info">
    <!-- Default panel contents -->
    <div class="panel-heading">Sent Invoices
        <?php if($type != 'all'): ?>
            <a href="<?= $this->url->get("request/sentrequests/all"); ?>" class="btn btn-success btn-xs" role="button">All</a>
            <div class="pull-right">
                <a href="<?= $this->url->get("request/cancel/all"); ?>" class="btn btn-danger btn-xs" role="button">Cancel All</a>
            </div>
        <?php else: ?>
            <a href="<?= $this->url->get("request/sentrequests/restricted"); ?>" class="btn btn-success btn-xs" role="button">Only Sent</a>
        <?php endif; ?>
    </div>

    <!-- Table -->
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>To user</th>
            <th>Item</th>
            <th>Type</th>
            <th>Status</th>
            <th>Created At</th>
            <th>Updated At</th>
            <th>Updated By</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($requests as $request): ?>
            <?php
            /**
             * @var Requests $request
             */
            ?>

            <tr class="active">
                <td><?= $request->toUser ? $request->toUser->username : '' ?></td>
                <td><?= ($request->item_id && $request->item) ? $request->item->name : '' ?></td>
                <td><?= $request->getTypeValue() ?></td>
                <td><?= $request->printStatus() ?></td>
                <td><?= $request->created_at ?></td>
                <td><?= $request->updated_at ?></td>
                <td><?= $request->updatedBy ? $request->updatedBy->username : ''  ?></td>
                <td>
                    <?php if($request->isStatusSent()): ?>
                        <a href="<?= $this->url->get("request/cancel/{$request->id}"); ?>" class="btn btn-danger btn-xs btn-action" role="button">Cancel</a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?= $pagination->generatePagination() ?>

