<?php
/**
 * @var Users $current_user
 * @var Users[] $users
 */
?>

<h3>Current HKT Status</h3>
<hr>
<div class="row">
    <div class="col-sm-6 col-lg-3">
        Total users: <span class="text-primary"><?= $total_user ?></span>
    </div>
    <div class="col-sm-6 col-lg-3">
        Total users wallet: <span class="text-primary"><?= $total_wallet ?></span>
    </div>
    <div class="col-sm-6 col-lg-3">
        Total users hcoin: <span class="text-primary"><?= $total_hcoin ?></span>
    </div>
    <div class="col-sm-6 col-lg-3">
        Total success invoices: <span class="text-primary"><?= $total_success_invoices ?></span>
    </div>
    <div class="col-sm-6 col-lg-3">
        Total success invoices amount: <span class="text-primary"><?= $total_success_invoices_amount ?></span>
    </div>
    <div class="col-sm-6 col-lg-3">
        Total unaccepted invoices amount: <span class="text-primary"><?= $total_unaccepted_invoices_amount ?></span>
    </div>
</div>
<br>
<br>

<h3>Administrator Status</h3>
<hr>
<h4>Current Admins Funds (<?= ($deposit_total - $withdraw_total) ?>)</h4>
<div class="row">
    <?php foreach ($current_wallet as $user_id => $wallet): ?>
        <?php $user = Users::findFirst($user_id) ?>
        <div class="col-sm-6 col-lg-3">
            <?= $user->getViewLink() ?>: <span class="text-primary"><?= $wallet ?></span>
        </div>
    <?php endforeach; ?>
</div>

<h4>Deposit (<?= $deposit_total ?>) </h4>
<div class="row">
    <?php foreach ($deposits as $deposit): ?>
        <?php $user = Users::findFirst($deposit->updated_by) ?>
        <div class="col-sm-6 col-lg-3">
            <?= $user->getViewLink() ?>: <span class="text-primary"><?= $deposit->sumatory ?></span>
        </div>
    <?php endforeach; ?>
</div>

<h4>Withdraw (<?= $withdraw_total ?>)</h4>
<div class="row">
    <?php foreach ($withdraws as $withdraw): ?>
        <?php $user = Users::findFirst($withdraw->updated_by) ?>
        <div class="col-sm-6 col-lg-3">
            <?= $user->getViewLink() ?>: <span class="text-primary"><?= $withdraw->sumatory ?></span>
        </div>
    <?php endforeach; ?>
</div>

<h3>HKT SALES</h3>
<hr/>
<span>(Current Admins Funds - Total users wallet - Total unaccepted invoices amount - Total users hcoin)</span><br>
<h4><?= $deposit_total - $withdraw_total . ' - ' . $total_wallet . ' - ' . $total_unaccepted_invoices_amount . ' - ' . $total_hcoin . ' = ' ?>
<span class="text-danger"><strong><?= $deposit_total - $withdraw_total - $total_wallet - $total_unaccepted_invoices_amount - $total_hcoin ?></strong></span></h4>

<hr>