<h1> FAQ </h1>
<hr>
<div class="jumbotron">
    <h2 class="text-info">What is Framgia Hyakkaten</h2>
    <p>The Hyakkaten (百貨店) in Japanese means "department store" (Cửa hàng bách hoá).<br>
        And the purpose of this service is to provide Framgia's Members a store where they can buy or sell what they want.<br>
        Framgia Hyakkaten is powered by the PhalconPHP Framework.</p>
</div>
<div class="jumbotron">
    <h2 class="text-info">Why couldn't I access to any pages after logging in ?</h2>
    <p>Because Framgia Hyakkaten is a restricted service, your account needs to be authorized.<br>
        So please use an ease-to-realize username and email when register.<br>
        After that please contact the administrators  to authorize it for you.</p>
</div>
<div class="jumbotron">
    <h2 class="text-info">Why do I have to pay 105% when deposit money to my wallet at Hyakkaten</h2>
    <p>Do not be so self-interested :D You should pay fee for the staffs who manage the system as well as the staffs who providing you goods.</p>
</div>
<div class="jumbotron">
    <h2 class="text-info">Do I receive 105% when I withdraw money from Hyakkaten ?</h2>
    <p>Sorry, the answer is "No". You will only receive 100.000 VND when you withdraw 100.000 VND from your wallet.</p>
</div>
<div class="jumbotron">
    <h2 class="text-info">Beside the main wallet, I also have some "hkt", what does it mean ?</h2>
    <p>The "hkt" is the Framgia Hyakkaten's virtual money. You can use it to buy goods in Framgia Hyakkaten, but you can not change it to real money (VND). It can not be withdrawn.</p>
</div>
<div class="jumbotron">
    <h2 class="text-info">How can I gain "hkt" ?</h2>
    <p>You can receive "hkt" when you buy goods in Hyakkaten. In general, you will receive 1 "hkt" after purchasing 100 VND.<br>
        During special campaign, you can receive more than that rate.</p>
</div>
<div class="jumbotron">
    <h2 class="text-info">Why didn't I receive any "hkt" after purchasing an item ?</h2>
    <p>After purchasing an item, an invoices will be created, and your wallet will be deducted. But it does not mean the transaction had been completed. You can still <span class="text-danger">CANCEL</span> the invoice to get your money back.<br>
        Or because of some reason, your invoice can be <span class="text-warning">REJECTED</span> by the seller, so at that time you will also get the refund.<br>
        Only when the invoice is <span class="text-success">ACCEPTED</span> by the seller, the transaction is considered as <span class="text-primary">COMPLETED</span>, and you can not get the refund any more. But at that time, you will receive "hkt".</p>
</div>
<div class="jumbotron">
    <h2 class="text-info">I want to sell a good, what do I need to do ?</h2>
    <p>At first, you should check the currently available items in the item page. If the item you want to sell has already existed, you can send request to become the seller of that item.
        After the administrator accepts your request, you can sell it to other members.</p>
</div><div class="jumbotron">
    <h2 class="text-info">I have created an item but why doesn't it appear in my selling items list ?</h2>
    <p>After you create an item, by default it will be unavailable which means that it will not appear in your selling items page, and it also be unavailable for other members to access.<br>
        Your item need to be checked by the administrator. If it is OK, it will become available, and then you can start selling it.<br>
        So if you have waited too long, fell free to contact the administrators :D</p>
</div>
<div class="jumbotron">
    <h2 class="text-info">Can I send money to other accounts ?</h2>
    <p>At that time, you can only send "hkt" to others.<br>
        Sending real money to other accounts will be available in the feature after we find an ease and secure way for users do it.</p>
</div>
<div class="jumbotron">
    <h2 class="text-info">I want to develop other services for Framgia Member, which sometime requires payment or something else like this. Do you provide API for me to make payment through Hyakkaten.
    </h2>
    <p>"Paying with HKT" is one of the interesting features that I really want to deploy :D<br>
        But it seems to be very hard for me to do it alone so that feature will not available in the near feature.
    </p>
</div><div class="jumbotron">
    <h2 class="text-info">I want to learn PHP. I want to learn Phalcon Framework. I want to help you to deploy more features to Framgia Hyakkaten. What should I do ? </h2>
    <p>Please fell free to contact me. You are welcome (dance)</p>
</div>




