<h1>Contact</h1>
<hr>
<div class="row">
    <div class="col-sm-4 col-lg-4">
        <div class="panel panel-info">
            <div class="panel-heading">
                Office
            </div>
            <div class="panel-body">
                <address>
                    <strong>Framgia Vietnam</strong><br>
                    13th Floor, Landmark 72 Tower<br>
                    Plot E6, Pham Hung Road, Cau Giay District, <br>
                    Hanoi, Vietnam<br>
                </address>
            </div>
        </div>

        <div class="panel panel-info">
            <div class="panel-heading">
                Email
            </div>
            <div class="panel-body">
                <p><span class="fa fa-envelope"></span> <a href="mailto:tran.duc.thang@framgia.com">tran.duc.thang@framgia.com</a></p>
                <p><span class="fa fa-envelope"></span> <a href="mailto:345@thangtd.com">345@thangtd.com</a></p>
            </div>
        </div>
    </div>
    <div class="col-12 col-lg-8">

        <div class="panel">
            <div class="panel-heading">
                <h3 class="text-primary">
                    Feel free to contact us
                </h3>
            </div>
            <div class="panel-body">
                <!-- CONTACT FORM -->
                <form id="ajax-contacts" class="" method="post">
                    <fieldset>
                        <?php if (!isset($current_user)): ?>
                            <div class="form-group">
                                <label for="name">Name</label><input class="form-control" type="text" name="name" value="">
                            </div>
                            <div class="form-group">
                                <label for="email">E-Mail</label><input class="form-control" type="text" name="email" value=""><br>
                            </div>
                        <?php endif; ?>
                        <div class="form-group">
                            <label for="subject">Subject</label><input class="form-control" type="text" name="subject" value=""><br>
                        </div>
                        <div class="form-group">
                            <label for="message">Comments</label><textarea class="form-control" name="message" rows="5" cols="25"></textarea><br>
                        </div>
                        <div class="form-group">
                            <label for="submit">&nbsp;</label><input class="btn btn-md btn-info" type="submit" name="submit" value="Send Message">
                        </div>
                        <fieldset>
                </form>
                <!-- END CONTACT FORM -->
            </div>
        </div>
    </div>
</div>
