<?php
/**
 * @var Users|null $current_user
 */
?>
<?= $this->getContent(); ?>
<div class="container">
    <div class="jumbotron">
        <h2 class="text-center"> WELCOME TO </h2>
        <h1 class="text-center"> FRAMGIA'S HYAKKATEN </h1>
        <ul>
            <?php if (!$current_user): ?>
                <li><h3><a href="<?= $this->url->get('user/register') ?>">Register</a></h3></li>
                <li><h3><a href="<?= $this->url->get('user/login') ?>">Login</a></h3></li>
                <li><h3><a href="<?= $this->facebook->getLoginUrl(['scope' => $this->config->facebook->scope, 'redirect_uri' => $this->url->get('user/facebook')]) ?>">Login with Facebook</a></h3></li>
                <li><h3><a href="<?= $this->url->get('user/forgotpassword') ?>">Forgot your password ?</a></h3></li>
            <?php endif; ?>
            <li><h3><a href="<?= $this->url->get('faq') ?>">FAQs</a></h3></li>
            <li><h3><a href="<?= $this->url->get('contact') ?>">Contact</a></h3></li>
        </ul>
    </div>
</div>
