<?php
/**
 * @var Users $current_user
 */
?>
<!-- Table -->
<table class="table table-striped table-hover">
    <thead>
    <tr>
        <th>Buyer</th>
        <th>Seller</th>
        <th>Shop</th>
        <th>Amount</th>
        <th>Price</th>
        <th>Status</th>
        <th>Created At</th>
        <th>Updated At</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($invoices as $invoice): ?>
        <?php
        /**
         * @var Invoices $invoice
         */
        ?>

        <tr class="active">
            <td><?= $invoice->fromUser ? $invoice->fromUser->username : '' ?></td>
            <td><?= $invoice->toUser ? $invoice->toUser->username : '' ?></td>
            <td>SHOP HERE</td>
            <td><?= $invoice->item_count ?></td>
            <td><?= $invoice->price ?></td>
            <td><?= $invoice->printStatus() ?></td>
            <td><?= $invoice->created_at ?></td>
            <td><?= $invoice->updated_at ?></td>
            <td>
                <?php if($invoice->isStatusSent() && $current_user->canAcceptInvoice($invoice)): ?>
                    <div class="btn-group-xs">
                        <a href="<?= $this->url->get("invoice/accept/{$invoice->id}"); ?>" class="btn btn-primary" role="button">Accept</a>
                        <a href="<?= $this->url->get("invoice/reject/{$invoice->id}"); ?>" class="btn btn-danger" role="button">Reject</a>
                    </div>
                <?php elseif($invoice->isStatusSent() && $current_user->canCancelInvoice($invoice)): ?>
                    <a href="<?= $this->url->get("invoice/cancel/{$invoice->id}"); ?>" class="btn btn-danger btn-xs" role="button">Cancel</a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


