<?php
/**
 * @var Users $current_user
 * @var Invoices[] $invoices
 */
$count = 0;
?>
<table class="table table-striped table-hover">
    <thead>
    <tr>
        <th>#</th>
        <th>User</th>
        <th>Item</th>
        <?php if (!empty($has_set)): ?>
            <th>Set</th>
        <?php endif; ?>
        <th>Amount</th>
        <th>Price</th>
        <th>Status</th>
        <?php if (empty($short)): ?>
            <th>Created At</th>
            <th>Updated At</th>
            <th>Updated By</th>
        <?php endif; ?>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($invoices as $invoice): ?>
        <?php
        /**
         * @var Invoices $invoice
         */
        ?>

        <tr class="" data-invoice-id="<?= $invoice->id ?>">
            <td class="invoice-order"><?= ++$count ?></td>
            <td class="invoice-from-user"><?= $invoice->fromUser ? $invoice->fromUser->getViewLink() : '' ?></td>
            <td class="invoice-item-name"><?= $invoice->item->name ?></td>
            <?php if (!empty($has_set)): ?>
                <td class="invoice-item-set">
                    <?php foreach ($invoice->getSetItems() as $item_shop): ?>
                        <?= $item_shop->item->name . ', ' ?>
                    <?php endforeach; ?>
                </td>
            <?php endif; ?>
            <td class="invoice-amount"><?= $invoice->item_count ?></td>
            <td class="invoice-price"><?= $invoice->price ?></td>
            <td class="invoice-status"><?= $invoice->printStatus() ?></td>
            <?php if (empty($short)): ?>
                <td class="invoice-created-at"><?= $invoice->created_at ?></td>
                <td class="invoice-updated-at"><?= $invoice->updated_at ?></td>
                <td class="invoice-updated-by"><?= $invoice->updated_by ? $invoice->updatedBy->getViewLink() : '' ?></td>
            <?php endif; ?>
            <td class="">
                <span class="invoice-action">
                <?php if((!isset($action) || !empty($action)) && $invoice->isStatusSent()): ?>
                    <button class="btn btn-primary btn-xs btn-action btn-invoice-status" data-invoice-id="<?= $invoice->id ?>" data-invoice-status="<?= Invoices::STATUS_ACCEPT ?>">Accept</button>
                    <button class="btn btn-danger btn-xs btn-action btn-invoice-status" data-invoice-id="<?= $invoice->id ?>" data-invoice-status="<?= Invoices::STATUS_REJECT ?>">Reject</button>
                <?php endif; ?>
                <?php if($current_user->id == $invoice->from_user_id && $invoice->isStatusSent()): ?>
                    <button class="btn btn-danger btn-xs btn-action btn-invoice-status" data-invoice-id="<?= $invoice->id ?>" data-invoice-status="<?= Invoices::STATUS_CANCEL ?>">Cancel</button>
                <?php endif; ?>
                </span>
                <a href="/invoice/view/<?= $invoice->id ?>" class="btn btn-info btn-xs btn-info" role="button">View</a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


