<?php
/**
 * @var Users $current_user
 * @var Invoices[] $invoices
 */
$count = 0;
?>
<table class="table table-striped table-hover">
    <thead>
    <tr>
        <th>To user</th>
        <th>To shop</th>
        <th>Item</th>
        <th>Sent</th>
        <th>Amount</th>
        <th>Price</th>
        <th>Status</th>
        <th>Created At</th>
        <th>Updated At</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($invoices as $invoice): ?>
        <?php
        /**
         * @var Invoices $invoice
         */
        ?>

        <tr class="" data-invoice-id="<?= $invoice->id ?>">
            <td class="invoice-to-user"><?= ($invoice->to_user_id && $invoice->toUser) ? $invoice->toUser->getViewLink() : '' ?></td>
            <td class="invoice-to-shop"><?= ($invoice->to_shop_id && $invoice->toShop) ? $invoice->toShop->name : '' ?></td>
            <td class="invoice-item"><?= $invoice->item->name ?></td>
            <td class="invoice-item-set">
                <?php foreach ($invoice->getSetItems() as $item_shop): ?>
                    <?= $item_shop->item->name . ', ' ?>
                <?php endforeach; ?>
            </td>
            <td class="invoice-amount"><?= $invoice->item_count ?></td>
            <td class="invoice-price"><?= $invoice->price ?></td>
            <td class="invoice-status"><?= $invoice->printStatus() ?></td>
            <td class="invoice-created-at"><?= $invoice->created_at ?></td>
            <td class="invoice-updated-at"><?= $invoice->updated_at ?></td>
            <td class="invoice-action">
                <?php if($invoice->from_user_id == $current_user->id && $invoice->isStatusSent()): ?>
                    <button class="btn btn-danger btn-xs btn-action btn-invoice-status" data-invoice-id="<?= $invoice->id ?>" data-invoice-status="<?= Invoices::STATUS_CANCEL ?>">Cancel</button>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


