<?php
/**
 * @var Users $current_user
 */
echo $this->getContent();
?>
<div class="panel panel-<?= $type == Invoices::TYPE_SENT ? 'info' : 'warning' ?>">
    <!-- Default panel contents -->
    <div class="panel-heading"><?= $type == Invoices::TYPE_SENT ? 'Sent' : 'Received' ?> Invoices</div>

    <!-- Table -->
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <?php if ($type == Invoices::TYPE_SENT): ?>
                <th>To user</th>
            <?php else: ?>
                <th>From user</th>
            <?php endif; ?>
            <th>To shop</th>
            <th>Item</th>
            <th>Amount</th>
            <th>Price</th>
            <th>Status</th>
            <th>Created At</th>
            <th>Updated At</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($invoices as $invoice): ?>
            <?php
            /**
             * @var Invoices $invoice
             */
            ?>

            <tr class="active">
                <?php if ($type == Invoices::TYPE_SENT): ?>
                    <td><?= $invoice->toUser ? $invoice->toUser->username : '' ?></td>
                <?php else: ?>
                    <td><?= $invoice->fromUser ? $invoice->fromUser->username : '' ?></td>
                <?php endif; ?>
                <td>SHOP HERE</td>
                <td><?= $invoice->item->name ?></td>
                <td><?= $invoice->item_count ?></td>
                <td><?= $invoice->price ?></td>
                <td><?= $invoice->printStatus() ?></td>
                <td><?= $invoice->created_at ?></td>
                <td><?= $invoice->updated_at ?></td>
                <td>
                    <?php if($type == Invoices::TYPE_SENT && $invoice->isStatusSent()): ?>
                        <a href="<?= $this->url->get("invoice/cancel/{$invoice->id}"); ?>" class="btn btn-danger btn-sm" role="button">Cancel</a>
                    <?php elseif($type != Invoices::TYPE_SENT && $invoice->isStatusSent()): ?>
                        <a href="<?= $this->url->get("invoice/accept/{$invoice->id}"); ?>" class="btn btn-primary btn-sm" role="button">Accept</a>
                        <a href="<?= $this->url->get("invoice/reject/{$invoice->id}"); ?>" class="btn btn-danger btn-sm" role="button">Reject</a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>


