<?php
/**
 * @var Users $current_user
 */
?>
<div class="panel panel-<?= $type == Invoices::TYPE_SENT ? 'info' : 'warning' ?>">
    <!-- Default panel contents -->
    <div class="panel-heading"><?= $type == Invoices::TYPE_SENT ? 'Sent' : 'Received' ?> Invoices</div>

    <!-- Table -->
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>#</th>
            <th>From user</th>
            <th>To user</th>
            <th>To shop</th>
            <th>Item</th>
            <th>Amount</th>
            <th>Price</th>
            <th>Status</th>
            <th>Created At</th>
            <th>Updated At</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($invoices as $invoice): ?>
            <?php
            /**
             * @var Invoices $invoice
             */
            ?>

            <tr class="active">
                <td><?= $invoice->id ?></td>
                <td><?= $invoice->fromUser ? $invoice->fromUser->username : '' ?></td>
                <td><?= $invoice->toUser ? $invoice->toUser->username : '' ?></td>
                <td>SHOP HERE</td>
                <td><?= $invoice->item->name ?></td>
                <td><?= $invoice->item_count ?></td>
                <td><?= $invoice->price ?></td>
                <td><?= $invoice->printStatus() ?></td>
                <td><?= $invoice->created_at ?></td>
                <td><?= $invoice->updated_at ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>


