<?php
/**
 * @var Users $current_user
 */
echo $this->getContent();
?>
<div class="panel panel-info">
    <!-- Default panel contents -->
    <div class="panel-heading">Sent Invoices
        <?php if($type != 'all'): ?>
            <a href="<?= $this->url->get("invoice/sentinvoices/all"); ?>" class="btn btn-success btn-xs" role="button">All</a>
            <div class="pull-right">
                <button class="btn btn-danger btn-xs btn-invoice-status-all" data-invoice-status="<?= Invoices::STATUS_CANCEL ?>">Cancel All</button>
            </div>
        <?php else: ?>
            <a href="<?= $this->url->get("invoice/sentinvoices/restricted"); ?>" class="btn btn-success btn-xs" role="button">Only Sent</a>
        <?php endif; ?>
    </div>

    <?= $this->partial('invoice/_sent_list', ['invoices' => $invoices]) ?>

</div>

<?= $pagination->generatePagination() ?>
