<?php
/**
 * @var Users $current_user
 */
echo $this->getContent();
?>
<div class="panel panel-info">
    <!-- Default panel contents -->
    <div class="panel-heading">Sent Invoices
        <?php if(!$type): ?>
            <a href="<?= $this->url->get("invoice/sentinvoices/all"); ?>" class="btn btn-success btn-xs" role="button">All</a>
            <div class="pull-right">
                <a href="<?= $this->url->get("invoice/cancel/all"); ?>" class="btn btn-danger btn-xs" role="button">Cancel All</a>
            </div>
        <?php else: ?>
            <a href="<?= $this->url->get("invoice/sentinvoices"); ?>" class="btn btn-success btn-xs" role="button">Only Sent</a>
        <?php endif; ?>
    </div>

    <!-- Table -->
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>To user</th>
            <th>To shop</th>
            <th>Item</th>
            <th>Amount</th>
            <th>Price</th>
            <th>Status</th>
            <th>Created At</th>
            <th>Updated At</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($invoices as $invoice): ?>
            <?php
            /**
             * @var Invoices $invoice
             */
            ?>

            <tr class="active">
                <td><?= $invoice->toUser ? $invoice->toUser->username : '' ?></td>
                <td>SHOP HERE</td>
                <td><?= $invoice->item->name ?></td>
                <td><?= $invoice->item_count ?></td>
                <td><?= $invoice->price ?></td>
                <td><?= $invoice->printStatus() ?></td>
                <td><?= $invoice->created_at ?></td>
                <td><?= $invoice->updated_at ?></td>
                <td>
                    <?php if($invoice->isStatusSent()): ?>
                        <a href="<?= $this->url->get("invoice/cancel/{$invoice->id}"); ?>" class="btn btn-danger btn-sm" role="button">Cancel</a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>


