<?php use Phalcon\Tag;

/**
 * @var Users $current_user
 * @var Invoices $invoice
 */
echo $this->getContent(); ?>

<h2>Invoice <?= $invoice->id ?> <?= $invoice->printStatus() ?></h2>
<div class="row">
    <div class="col-lg-4 col-xs-12">
        <div class="row>"><?= $this->partial('item/_an_item', ['item' => $invoice->item]) ?></div>
        <div class="row>"><?= $invoice->to_shop_id ? $this->partial('shop/_a_shop', ['shop' => $invoice->toShop, 'no_container_div' => true]) : '' ?></div>
    </div>
    <div class="col-lg-8 col-xs-12">
        <table class="table table-hover">
            <tr>
                <th>From User</th>
                <td><?= $invoice->fromUser->getViewLink() ?></td>
            </tr>
            <tr>
                <th>To User</th>
                <td><?= $invoice->to_user_id ? $invoice->toUser->getViewLink() : '' ?></td>
            </tr>
            <tr>
                <th>Item Amout</th>
                <td><?= $invoice->item_count ?></td>
            </tr>
            <tr>
                <th>Price</th>
                <td><?= $invoice->price ?></td>
            </tr>
            <tr>
                <th>HCoin Receive</th>
                <td><?= $invoice->hcoin_receive ?></td>
            </tr>
            <tr>
                <th>Updated By</th>
                <td><?= $invoice->updated_by ? $invoice->updatedBy->getViewLink() : '' ?></td>
            </tr>
            <tr>
                <th>Created At</th>
                <td><?= $invoice->created_at ?></td>
            </tr>
            <tr>
                <th>Updated At</th>
                <td><?= $invoice->updated_at ?></td>
            </tr>
        </table>
        <div class="isotype-container">
            <?php foreach($invoice->getSetItems() as $item_shop): ?>
                <div class="col-sm-6 col-md-4 isotype-item"><?= $this->partial('item/_an_item', ['item' => $item_shop->item]) ?></div>
            <?php endforeach; ?>
        </div>
    </div>
    </td>
    </div>
</div>
