<?php
/**
 * @var Users $current_user
 * @var Shops $shop
 */
?>

<?php if (!isset($no_container_div)): ?>
    <div class="col-md-6 col-lg-4">
<?php endif; ?>
    <div class="thumbnail">
        <div class="thumbnail-detail">
            <span class="row">
                <a href="<?= $this->url->get("shop/view/{$shop->id}"); ?>"><span class="item-name text-warning"><?= $shop->name ?></span></a>
            </span>
            Manager: <?= $shop->user->getUserDisplayName() ?>
        </div>
        <?= $shop->imageView() ?>
    </div>
<?php if (!isset($no_container_div)): ?>
    </div>
<?php endif; ?>