<?php
use Phalcon\Tag;

/**
 * @var Shops[] $shop
 * @var Users $current_user
 * @var Pagination $pagination
 */

echo $this->getContent();
?>
<?php if(count($shops)): ?>
    <h1>Open Shops </h1>
    <hr>
    <div class="row">
        <?php foreach($shops as $shop): ?>
            <div class="col-md-6 col-lg-4">
                <div class="thumbnail">
                    <div class="thumbnail-detail">
                        <span class="row shop-name text-primary"><?= $shop->name ?></span>
                        Manager: <?= $shop->user->username ?>
                        <a href="<?= $this->url->get("shop/view/{$shop->id}"); ?>" class="btn btn-info btn-sm" role="button">View</a>
                    </div>
                    <?= $shop->imageView() ?>
                </div>
            </div>
        <?php endforeach ?>
    </div>
<?php else: ?>
    <h1>No Shop available !</h1>
    <hr>
<?php endif; ?>

<?= $pagination->generatePagination() ?>