<?php
use Phalcon\Tag;

/**
 * @var Shops[] $shop
 * @var Users $current_user
 * @var Pagination $pagination
 */

echo $this->getContent();
?>
<?php if(count($shops)): ?>
    <h1>Open Shops </h1>
    <hr>
    <div class="row">
        <?php foreach($shops as $shop): ?>
            <?= $this->partial('shop/_a_shop', ['shop' => $shop]); ?>
        <?php endforeach ?>
    </div>
<?php else: ?>
    <h1>No Shop available !</h1>
    <hr>
<?php endif; ?>

<?= $pagination->generatePagination() ?>