<?php use Phalcon\Tag;

echo Tag::stylesheetLink('css/bootstrap-datetimepicker.min.css');
echo Tag::javascriptInclude('js/moment.min.js');
echo Tag::javascriptInclude('js/bootstrap-datetimepicker.min.js');?>
<div class="row">
    <?= $this->getContent(); ?>
    <h2>Update item <?= $shop->name ?></h2>
    <hr>
    <?php $this->partial('shop/_form', ['link' => "shop/update/$shop->id", 'button' => 'Save']) ?>
</div>