<?php use Phalcon\Tag;

/**
 * @var Users $current_user
 * @var Shops $shop
 * @var ItemShops $item_shops
 */
echo $this->getContent(); ?>

<div class="row">
    <div class="col-lg-4 col-xs-12">
        <?= $shop->imageView() ?>
    </div>
    <div class="col-lg-8 col-xs-12">
        <table class="table table-hover">
            <tr>
                <th class="success"><?= $shop->getAttributeLabel('name') ?></th>
                <td><?= $shop->name ?></td>
            </tr>
            <tr>
                <th class="success"><?= $shop->getAttributeLabel('status') ?></th>
                <td><?= $shop->getStatusValue() ?></td>
            </tr>
            <tr>
                <th class="success">Owner</th>
                <td><?= $shop->user->username ?></td>
            </tr>
            <tr>
                <th class="success"><?= $shop->getAttributeLabel('description') ?></th>
                <td><?= $shop->description ?></td>
            </tr>
            <tr>
                <th class="success"><?= $shop->getAttributeLabel('created_at') ?></th>
                <td><?= $shop->created_at ?></td>
            </tr>
            <tr>
                <th class="success">Action</th>
                <td>
                    <div class="btn-group-xs">
                        <?php if ($current_user->canEditShop($shop)) : ?>
                            <a href="<?= $this->url->get("shop/update/{$shop->id}")?>" class="btn btn-warning btn-action"><i class="fa fa-edit"></i> Edit </a>
                        <?php endif; ?>
                        <?php if ($current_user->canCreateShopStaffRequest($shop)): ?>
                            <button class='btn btn-primary btn-action shop-sell-request' id="shop-sell-request-<?= $shop->id ?>" data-shop-id='<?= $shop->id ?>'>Sent Request to be a staff of this shop</button>
                        <?php endif; ?>
                        <?php if ($shop->checkOwnerOrStaff($current_user)): ?>
                            <a href="<?= $this->url->get("item/create/{$shop->id}")?>" class="btn btn-primary btn-action"> Create Item </a>
                            <a href="<?= $this->url->get("item/shop/{$shop->id}")?>" class="btn btn-primary btn-action"> View list Items </a>
                            <a href="<?= $this->url->get("shop/changestatus/{$shop->id}/" . Shops::STATUS_OPEN)?>" class="btn btn-success btn-action"> Set Open </a>
                            <a href="<?= $this->url->get("shop/changestatus/{$shop->id}/" . Shops::STATUS_NORMAL)?>" class="btn btn-info btn-action"> Set Normal </a>
                            <a href="<?= $this->url->get("shop/changestatus/{$shop->id}/" . Shops::STATUS_CLOSE)?>" class="btn btn-danger btn-action"> Set Close </a>
                        <?php endif; ?>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</div>
<hr>

<?php if (!$item_shops || count($item_shops) == 0): ?>
    <h2 class="text-warning"> No Items Available </h2>
<?php else: ?>
    <h2 class="text-warning"> On Sale </h2>
    <?php foreach ($item_shops as $item_shop): ?>
    <div class="col-sm-6 col-md-4 col-lg-3">
        <div class="thumbnail single-item-select" data-form="item" data-item-shop-id="<?= $item_shop->id ?>">
            <div class="thumbnail-detail">
                <a href="<?= $this->url->get("item/view/{$item_shop->item->id}"); ?>"><span class="item-name text-warning"><?= $item_shop->item->name ?></span></a>
            </div>
            <?= $item_shop->item->imageView() ?>
        </div>
    </div>
    <?php endforeach; ?>
<?php endif; ?>
