<?php use Phalcon\Tag;

/**
 * @var Users $current_user
 * @var Shops $shop
 * @var ItemShops $item_shops
 * @var bool $favorite
 */
echo $this->getContent();

$can_edit_shop = $current_user->canEditShop($shop);
$action = $shop->checkOwnerOrStaff($current_user);
?>

<h2 class="text-primary">
    <?= $shop->name ?>
    <?= ViewHelper::likeButton($shop, $favorite) ?>
</h2>
<div class="row">
    <div class="col-lg-4 col-xs-12">
        <?= $shop->imageView() ?>
    </div>
    <div class="col-lg-8 col-xs-12">
        <table class="table table-hover">
            <?php if ($can_edit_shop): ?>
                <tr>
                    <th class="success"><?= $shop->getAttributeLabel('sales') ?></th>
                    <td><?= $shop->sales ?></td>
                </tr>
            <?php endif; ?>
            <tr>
                <th class="success"><?= $shop->getAttributeLabel('status') ?></th>
                <td><?= $shop->getStatusValue() ?></td>
            </tr>
            <tr>
                <th class="success">Founder</th>
                <td><?= $shop->user->getViewLink() ?></td>
            </tr>
            <tr>
                <th class="success">Staff</th>
                <td>
                    <?php foreach ($shop->shopStaffs as $user): ?>
                        <?= $user->getViewLink() ?>
                    <?php endforeach ?>
                </td>
            </tr>
            <tr>
                <th class="success"><?= $shop->getAttributeLabel('description') ?></th>
                <td><?= $shop->description ?></td>
            </tr>
            <tr>
                <th class="success"><?= $shop->getAttributeLabel('created_at') ?></th>
                <td><?= $shop->created_at ?></td>
            </tr>
            <tr>
                <th class="success">Action</th>
                <td>
                    <div class="btn-group-xs">
                        <?php if ($can_edit_shop) : ?>
                            <a href="<?= $this->url->get("shop/update/{$shop->id}")?>" class="btn btn-warning btn-action"><i class="fa fa-edit"></i> Edit </a>
                        <?php endif; ?>
                        <?php if ($current_user->canCreateShopStaffRequest($shop)): ?>
                            <button class='btn btn-primary btn-action shop-sell-request' id="shop-sell-request-<?= $shop->id ?>" data-shop-id='<?= $shop->id ?>'>Sent Request to be a staff of this shop</button>
                        <?php endif; ?>
                        <?php if ($shop->checkOwnerOrStaff($current_user)): ?>
                            <a href="<?= $this->url->get("item/create/{$shop->id}")?>" class="btn btn-primary btn-action"> Create Item </a>
                            <a href="<?= $this->url->get("item/shop/{$shop->id}")?>" class="btn btn-primary btn-action"> View list Items </a>
                            <a href="<?= $this->url->get("shop/invoices/{$shop->id}")?>" class="btn btn-primary btn-action"> View All Invoices </a>
                            <a href="<?= $this->url->get("shop/changestatus/{$shop->id}/" . Shops::STATUS_OPEN)?>" class="btn btn-success btn-action"> Set Open </a>
                            <a href="<?= $this->url->get("shop/changestatus/{$shop->id}/" . Shops::STATUS_NORMAL)?>" class="btn btn-info btn-action"> Set Normal </a>
                            <a href="<?= $this->url->get("shop/changestatus/{$shop->id}/" . Shops::STATUS_CLOSE)?>" class="btn btn-danger btn-action"> Set Close </a>
                        <?php endif; ?>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</div>
<hr>

<?php if (!$item_shops || count($item_shops) == 0): ?>
    <h2 class="text-warning"> No Items Available </h2>
<?php else: ?>
    <?php $set = []; ?>
    <h2 class="text-warning"> On Sale </h2>
    <div class="row isotype-container">
    <?php foreach ($item_shops as $item_shop): ?>
        <?php if ($item_shop->item->isNormalItem()): ?>
            <div class="col-sm-6 col-md-4 col-lg-3 isotype-item">
                <div class="thumbnail single-item-select" data-form="item" data-item-shop-id="<?= $item_shop->id ?>">
                    <div class="thumbnail-detail">
                        <a href="<?= $this->url->get("item/view/{$item_shop->item->id}"); ?>"><span class="item-name"><?= $item_shop->item->name . ' (' . $item_shop->getSalePrice() . ')' ?></span></a>
                    </div>
                    <?= $item_shop->item->imageView() ?>
                </div>
            </div>
            <script type="text/javascript">
                localStorage.setItem("item-shop-" + <?= $item_shop->id ?>, JSON.stringify(<?= $item_shop->getItemJsonObject() ?>));
            </script>
        <?php elseif($item_shop->item->isSetItem()): ?>
            <?php
                $set[] = $item_shop;
            ?>
        <?php endif; ?>
    <?php endforeach; ?>
    </div>
    <?php if (count($set)): ?>
        <hr>
        <div class="row isotype-container">
        <?php foreach ($set as $item_shop): ?>
            <div class="col-sm-4 col-md-2 isotype-item">
                <div class="thumbnail multi-item-select" data-form="item_set" data-item-shop-id="<?= $item_shop->id ?>">
                    <div class="thumbnail-detail-small">
                        <a href="<?= $this->url->get("item/view/{$item_shop->item->id}"); ?>"><span class="item-name "><?= $item_shop->item->name ?></span></a>
                    </div>
                    <img src="<?= $item_shop->item->getImageLink() ?>" class="multi-item-select-img">
                </div>
            </div>
            <script type="text/javascript">
                localStorage.setItem("item-shop-" + <?= $item_shop->id ?>, JSON.stringify(<?= $item_shop->getItemJsonObject() ?>));
            </script>
        <?php endforeach ?>
        </div>
    <?php endif; ?>
    <div class="row">
        <div class="col-md-6 col-lg-3">
            <div class="input-group">
                <input type="number" name="amount" id="item-shop-amount" class="form-control" value="1">
                <span class="input-group-btn">
                    <button class="btn btn-primary" id = "shop-buy-btn">Buy Now</button>
                </span>
            </div>
        </div>
    </div>
<?php endif; ?>

<hr>
<h2 class="text-success"> Today Invoices </h2>

<?php foreach(Users::$place_value as $place => $place_name): ?>
    <?php if (!empty($invoices_filter[$place])): ?>
        <div class="panel panel-warning">
            <div class="panel-heading">
                Received Invoices from <?= $place_name ?>
                <?php if (!empty($action)): ?>
                    <div class="btn-group-xs pull-right">
                        <button class="btn btn-primary btn-xs btn-invoice-status-all" data-invoice-status="<?= Invoices::STATUS_ACCEPT ?>">Accept All</button>
                        <button class="btn btn-danger btn-xs btn-invoice-status-all" data-invoice-status="<?= Invoices::STATUS_REJECT ?>">Reject All</button>
                    </div>
                <?php endif; ?>
            </div>
            <?= $this->partial('invoice/_received_list', ['invoices' => $invoices_filter[$place], 'action' => $action, 'has_set' => true, 'short' => true, 'index' => true]); ?>
        </div>
    <?php endif; ?>
<?php endforeach; ?>