<?php
/**
 * @var int $count
 */
?>
<tbody>
	<tr>
		<td style="padding:40px 0  0 0;">
			<p style="color:#000;font-size: 16px;line-height:24px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;font-weight:normal;">

				<h2 style="font-size: 14px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;">
                There <?= $count > 1 ? 'are' : 'is' ?> <?= $count ?> special invoice<?= $count > 1 ? 's' : '' ?> created recently !</h2>
                <br>
				<p style="font-size: 13px;line-height:24px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;">
                    Please check special invoices page for more information
                <br>
				</p>
                ------------------<br>
                <a href="http://hkt.thangtd.com">http://hkt.thangtd.com</a><br>
				FRAMGIA HKT TEAM !
				<br>
			</p>
		</td>
	</tr>
</tbody>

