<tbody>
	<tr>
		<td style="padding:40px 0  0 0;">
			<p style="color:#000;font-size: 16px;line-height:24px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;font-weight:normal;">

				<h2 style="font-size: 14px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;">Money Transfer Received</h2>

				<p style="font-size: 13px;line-height:24px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;">
					You have received <?= $amount ?> VND from <?= $sender ?> at <?= $updated_at ?><br>
					The transfer fee is paid by <?= $handler ?>.
					<br>
					<br>
					FRAMGIA HKT TEAM !
					<br>
			    </p>
			</p>
		</td>
	</tr>
</tbody>
