<tbody>
	<tr>
		<td style="padding:40px 0  0 0;">
			<p style="color:#000;font-size: 16px;line-height:24px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;font-weight:normal;">

				<h2 style="font-size: 14px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;">Money Transfer Confirmation</h2>

				<p style="font-size: 13px;line-height:24px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;">
					At <?= $created_at ?>, you have requested to transfer <?= $amount ?> VND to <?= $recipient ?>.<br>
					The transfer fee is paid by <?= $handler ?>.
					<br>
					Please click the link below to confirm or cancel your request. The link will be expired in <?= $expire_time ?> minutes.
					<br>
					<br>
					<a href="<?= $confirm_url ?>"><?= $confirm_url ?></a>
					<br>
					<br>
					FRAMGIA HKT TEAM !
					<br>
			    </p>
			</p>
		</td>
	</tr>
</tbody>
