<?php
/**
 * @var Users[] $users
 * @var Users $current_user
 */

$is_role_over = $current_user->isRoleOver(Users::ROLE_MODERATOR);
?>
<table class="table table-bordered">
    <th>Id</th>
    <th>Username</th>
    <th>Email</th>
    <th>Display Name</th>
    <th>Role</th>
    <?php if ($is_role_over): ?>
        <th>Wallet</th>
        <th>HCoin</th>
    <?php endif; ?>
    <th>Register Type</th>
    <th>Created</th>

    <?php foreach ($users as $user): ?>
        <tr>
            <td><?= $user->id ?></td>
            <td><?= $user->username ?></td>
            <td><?= $user->email ?></td>
            <td><?= $user->getUserDisplayName() ?></td>
            <td><?= $user->getRoleValue() ?></td>
            <?php if ($is_role_over): ?>
                <td><?= $user->wallet ?></td>
                <td><?= $user->hcoin ?></td>
            <?php endif; ?>
            <td><?= $user->getRegisterTypeValue() ?></td>
            <td><?= $user->created_at ?></td>
        </tr>
    <?php endforeach; ?>
</table>

