<?php
use Phalcon\Tag;

echo $this->getContent();
?>

<div align="left">
    <h2>Change Password</h2>
</div>
<hr>
<div class="center-block register-form">
	<?= Tag::form(['user/changepassword', 'method' => 'post']) ?>
    <div class="form-group">
        <?= $form->render('password', ['class' => 'form-control']) ?>
    </div>
    <div class="form-group">
        <?= $form->render('new_password', ['class' => 'form-control']) ?>
    </div>
    <div class="form-group">
        <?= $form->render('comfirm_password', ['class' => 'form-control']) ?>
    </div>
    <div class="row">
        <input type="submit" value="Submit" class="btn btn-primary">
    </div>
	</form>

</div>