<?php
use Phalcon\Tag;
echo $this->getContent();
/**
 * @var ItemShops[] $item_shops
 */
?>
<h1><span class="text-warning">Money Transfer Confirmation</span></h1>
<?php if ($valid_transfer): ?>
<table class="table table-bordered">
    <thead>
    <th>ID</th>
    <th>Recipient</th>
    <th>Transfer Amount</th>
    <th>Charged Amount</th>
    <th>Status</th>
    <th>Created at</th>
    </thead>
    <tbody>
        <tr>
            <td><?= $transfer->id ?></td>
            <td><?= $transfer->toUser->getViewLink() ?></td>
            <td><?= $transfer->transfer_amount ?> VND</td>
            <td><?= $transfer->charged_amount ?> VND</td>
            <td><?= $transfer->printStatus() ?> </td>
            <td><?= $transfer->created_at ?> </td>
        </tr>
    </tbody>
</table>
Are you sure to process this transfer ?
<?= Tag::form(["user/confirm_transfer/{$transfer->id}/{$auth}", 'method' => 'post', 'class' => 'form-confirm-transfer']) ?>
<?= $form->render('csrf', ['value' => $this->security->getToken()]) ?>
<input class="btn btn-primary" name="data[process]" id="confirm-transfer-btn" type="submit" value="Process"></input>
<input class="btn btn-danger" name="data[cancel]" id="confirm-transfer-btn" type="submit" value="Cancel"></input>
</form>
<?php else: ?>
    Either your transfer id is invalid or transfer is expired.
<?php endif; ?>