<?php
use Phalcon\Tag;

echo $this->getContent();
?>

<div align="left">
    <h2>Password Recovery</h2>
</div>
<hr>
<div class="center-block register-form">
	<?= Tag::form(["user/forgotpassword", 'method' => 'post']) ?>
    <div class="form-group">
        <?= $form->render('email', ['class' => 'form-control']) ?>
    </div>
    <div class="row">
        <input type="submit" value="Submit" class="btn btn-primary">
    </div>
	</form>

</div>