<?php
use Phalcon\Tag;

echo $this->getContent();
?>
<div class="center-block">
    <?= Tag::form(['user/login', 'method' => 'post', 'class' => 'form-signin']) ?>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h2 class="form-signin-heading">Login</h2>
        </div>
        <div class="panel-body">
            <?= $form->render('email', ['class' => 'form-control', 'autofocus']) ?>
            <?= $form->render('password', ['class' => 'form-control']) ?>
            <label class="checkbox">
                <?= $form->render('remember', ['class' => 'pull-left']) ?> Remember me
            </label>
        </div>
        <div class="panel-footer">
            <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
        </div>
    </div>
    </form>
</div>