<?php use Phalcon\Tag;

/**
 * @var Users $current_user
 */
echo $this->getContent(); ?>
<h2>Transfer Money</h2>
<?= Tag::form(['user/transfer', 'method' => 'post', 'class' => 'form-transfer form-horizontal', 'role' => 'form']) ?>
<div class="form-group">
    <label class="col-sm-2 control-label"><?= $form->label('target_user') ?></label>
    <div class="col-sm-10 col-lg-4">
        <?= $form->render('target_user', ['class' => 'form-control', 'autocomplete' => 'off']) ?>
        <?= $form->render('target_user_id', ['class' => 'form-control']) ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label"><?= $form->label('amount') ?></label>
    <div class="col-sm-10 col-lg-4">
        <?= $form->render('amount', ['class' => 'form-control']) ?>
        <span>(Current: <?= $current_user->wallet ?> VND )</span>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label"><?= $form->label('fee_bearer') ?></label>
    <div class="col-sm-10 col-lg-4">
        <?= $form->render('fee_bearer', ['class' => 'form-control']) ?>
        <span class="label label-danger">Note:</span> Transfer fee is <strong><span class="fee-ratio"><?= $fee_ratio ?></span>%</strong> of transfer amount.
    </div>
</div>

<?= $form->render('csrf', ['value' => $this->security->getToken()]) ?>
<div class="form-group">
    <div class="col-sm-10 col-lg-4 col-sm-offset-2">
        <button class="btn btn-primary btn-sm" id="transfer-money-btn" type="submit">Transfer</button>
    </div>
</div>
</form>
<br>
<script>
var json_data;
$.get('/user/all', function(data){
    json_data = data;
}, 'json');

$("#target_user").typeahead({
    source: function (query, process) {
        users = [];
        user_data = {};

        $.each(json_data, function (i, user) {
            user_data[user.full_name] = user;
            users.push(user.full_name);
        });
        $("#target_user_id").val('');
        process(users);
    },

    sorter: function (items) {
        return items.sort();
    },

    matcher: function (item) {
        if (item.toLowerCase().indexOf(this.query.trim().toLowerCase()) != -1) {
            return true;
        }
    },

    updater: function (item) {
        $("#target_user_id").val(user_data[item].user_id);
        return item;
    }
});
</script>

<h2>Transfer Logs</h2>
<?= $this->partial('transfer/_logs') ?>

<?= $pagination->generatePagination() ?>
