<?php
/**
 * @var Faqs[] $faqs
 * @var Users $current_user
 */
?>
<h1> FAQ </h1>
<hr>
<?php foreach($faqs as $faq): ?>
<div class="jumbotron">
    <h2 class="text-info"><?= $faq->question ?></h2>
    <p><?= $faq->answer ?></p>
    <?php if($current_user && $current_user->isRoleOver(Users::ROLE_ADMIN)):?>
        <a href="<?= $this->url->get("faq/update/{$faq->id}"); ?>" class="btn btn-info btn-sm" role="button">Edit</a>
    <?php endif; ?>
</div>
<?php endforeach; ?>