<?php
/**
 * @var BForm $form
 */
?>
<div class="item-form center-block">
<?php
    echo $form->start($link);
    echo $form->numericField('price');
    echo $form->selectStatic('status',  ItemShops::$status_value);
?>

    <div class="form-group">
        <label class="control-label">Start Sale Date</label>
        <div class='input-group date datetimepicker' data-default-date="<?= $form->model->start_sale_date ?>" data-date-format="YYYY-MM-DD HH:mm:ss">
            <input type='text' class="form-control" name="start_sale_date"/>
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label">End Sale Date</label>
        <div class='input-group date datetimepicker' data-default-date="<?= $form->model->end_sale_date ?>" data-date-format="YYYY-MM-DD HH:mm:ss">
            <input type='text' class="form-control" name="end_sale_date"/>
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
        </div>
    </div>
<?php
    echo $form->submitButton($button);
    echo $form->end();
?>
</div>

<script type="text/javascript">
    $(function () {
        $('.datetimepicker').each(function (index) {
            var default_date = $(this).attr('data-default-date');
            $(this).datetimepicker({
                pick12HourFormat: false,
                defaultDate: default_date
            });
        })
    });
</script>