<?php use Phalcon\Tag; ?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <?= Tag::getTitle(); ?>
        <?= Tag::stylesheetLink('css/bootstrap.min.css'); ?>
        <?= Tag::stylesheetLink('css/font-awesome.min.css'); ?>
        <?= Tag::stylesheetLink('css/style.css'); ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Your invoices">
        <meta name="author" content="Framgia HKT Team">
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon"/>
    </head>
    <body>
        <?php $this->partial('layouts/header') ?>
        <?= Tag::javascriptInclude('js/jquery.min.js'); ?>
        <?= Tag::javascriptInclude('js/bootstrap.min.js'); ?>
        <?= Tag::javascriptInclude('js/bootbox.min.js'); ?>
        <?= Tag::javascriptInclude('js/waitforimages.js'); ?>
        <?= Tag::javascriptInclude('js/isotope.pkgd.min.js'); ?>
        <?= Tag::javascriptInclude('js/main.js'); ?>
        <?php if (isset($current_page) && in_array($current_page, ['donate', 'transfer'])) : ?>
        <?= Tag::javascriptInclude('js/bootstrap3-typeahead.min.js'); ?>
        <?php endif; ?>
        <div class="container container-main">
            <?= $this->getContent() ?>
        </div>
    </body>
    <?php $this->partial('layouts/footer') ?>
</html>
<?php if ($user_announcements): ?>
<script>
    $(function() {
        <?php foreach ($user_announcements as $user_announcement): ?>
            var announcement = <?= $user_announcement->getJsonData() ?>;
            createAnnouncement(announcement);
        <?php endforeach; ?>
    });
</script>
<?php endif; ?>
