<footer>
    <div class="container container-footer">
        <hr>
        <div class="row text-center">
            Powered by <?= Phalcon\Tag::linkTo(['http://phalconphp.com/', 'PhalconPHP', 'local' => false]) ?>
        </div>
        <div class="row text-center">
            Copyright © <?= date('Y') ?> by HKT Group @ <?= Phalcon\Tag::linkTo(['http://framgia.com/en/', 'Framgia Vietnam', FALSE]) ?>
        </div>
    </div>
</footer>