<?php
use Phalcon\Tag;
?>
<footer>
    <div class="container container-footer">
        <hr>
        <div class="row text-center">
            <span class="fa fa-info-circle"></span> <?= Tag::linkTo(['faq', 'FAQs']) ?> -
            <span class="fa fa-envelope"></span> <?= Tag::linkTo(['contact', 'Contact']) ?>
        </div>
        <div class="row text-center">
            Powered by <?= Tag::linkTo(['http://phalconphp.com/', 'PhalconPHP', 'local' => false]) ?>
        </div>
        <div class="row text-center">
            Copyright © <?= date('Y') ?> by HKT Group @ <?= Tag::linkTo(['http://framgia.com/en/', 'Framgia Vietnam', FALSE]) ?>
        </div>
    </div>
</footer>