<?php use Phalcon\Tag;
/**
 * @var Users $current_user
 */
?>
<div class="navbar navbar-default navbar-fixed-top bs-docs-nav" role="banner">
    <div class="container">
        <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
            <ul class="nav navbar-nav">
                <li class="<?= $current_page === 'index' ? 'active' : '' ?>">
                    <a href="<?= $this->url->get('') ?>" class="navbar-brand">
                        <span class="fa fa-home"></span>
                        HKT
                    </a>
                </li>
            <?php if(isset($current_user)): ?>
                <li class="dropdown <?= $current_page === 'shop' ? 'active' : '' ?>">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="fa fa-shopping-cart"></span>
                        Shops <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="<?= $this->url->get('shop/open') ?>">Open Shops</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="<?= $this->url->get('shop/create') ?>"><span class="fa fa-edit"></span>Create New</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown <?= $current_page === 'item' ? 'active' : '' ?>">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="fa fa-coffee"></span>
                        Items <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="<?= $this->url->get('item/onsale') ?>">On Sale</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="<?= $this->url->get('item/available') ?>">Request Sell Items</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="<?= $this->url->get('item/create') ?>"><span class="fa fa-edit"></span>Create New</a>
                        </li>
                    </ul>
                </li>
                <li class="<?= $current_page === 'users' ? 'active' : '' ?>">
                    <a href="<?= $this->url->get('user') ?>">
                        <span class="fa fa-users"></span> Users
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <?php if ($current_user->role >= Users::ROLE_ADMIN): ?>
                <li class="<?= $current_page === 'setting' ? 'active' : '' ?>">
                    <a href="<?= $this->url->get('setting') ?>">
                        <span class="fa fa-cog"></span>
                        Setting (<?= $current_user->getRoleValue() ?>) </b>
                    </a>
                </li>
                <?php endif; ?>
                <li class="dropdown <?= $current_page === 'user' ? 'active' : '' ?>">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="fa fa-user"></span>
                        <span class="user-display-name"><?= $current_user->getUserDisplayName() ?></span> ! <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="<?= $this->url->get('request/sentrequests/restricted') ?>">Sent Requests</a>
                        </li>
                        <li>
                            <a href="<?= $this->url->get('request/receivedrequests/restricted') ?>">Received Request</a>
                        </li>
                        <li>
                            <a href="<?= $this->url->get('item/my') ?>">My Sale Items</a>
                        </li>
                        <li>
                            <a href="<?= $this->url->get('shop/my') ?>">My Shops</a>
                        </li>
                        <li>
                            <a href="<?= $this->url->get('user/favorite') ?>">My Favorite</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="<?= $this->url->get('user/view') ?>">My Profile Page</a>
                        </li>
                        <li>
                            <a href="<?= $this->url->get('user/changepassword') ?>">Change Password</a>
                        </li>
                        <li>
                            <a href="<?= $this->url->get('user/logout') ?>"><span class="fa fa-power-off"></span>Log out</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown <?= $current_page === 'wallet' ? 'active' : '' ?>">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="fa fa-dollar"></span>:
                        <span class="my-wallet"><?= $current_user->wallet ?></span> <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="<?= $this->url->get('item/special/1') ?>">Deposit</a>
                        </li>
                        <li>
                            <a href="<?= $this->url->get('item/special/2') ?>">Withdraw</a>
                        </li>
                        <li>
                            <a href="<?= $this->url->get('invoice/sentinvoices/restricted') ?>">Sent Invoices</a>
                        </li>
                        <li>
                            <a href="<?= $this->url->get('invoice/receivedinvoices/restricted') ?>">Received Invoices</a>
                        </li>
                        <?php if ($current_user->isRoleOver(Users::ROLE_ADMIN)): ?>
                            <li class="divider"></li>
                            <li>
                                <a href="<?= $this->url->get('invoice/special/restricted') ?>">Special Invoices</a>
                            </li>
                        <?php endif; ?>
                        <li class="divider"></li>
                        <li>
                            <a href="<?= $this->url->get('log/wallet') ?>">Wallet Logs</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown <?= $current_page === 'hcoin' ? 'active' : '' ?>">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        HCoin:
                        <?= $current_user->hcoin ?> <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="<?= $this->url->get('user/donate') ?>">Donate</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="<?= $this->url->get('log/hcoin') ?>">HCoin Logs</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <?php else: ?>
                <form class="navbar-form navbar-left" role="login" action="/user/login" method="post">
                    <div class="form-group">
                        <?= $login_form->render('email', ['class' => 'form-control', 'placeholder' => 'email/username']) ?>
                    </div>
                    <div class="form-group">
                        <?= $login_form->render('password', ['class' => 'form-control', 'placeholder' => 'password']) ?>
                    </div>
                    <button type="submit" class="btn btn-success"><span class="fa fa-sign-in"></span>Submit</button>
                </form>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="<?= $current_page === 'facebook' ? 'active' : '' ?>">
                    <a href="<?= $this->facebook->getLoginUrl(['scope' => $this->config->facebook->scope, 'redirect_uri' => $this->url->get('user/facebook')]) ?>">
                        <span class="fa"></span>
                        Facebook Login
                    </a>
                </li>
                <li class="<?= $current_page === 'register' ? 'active' : '' ?>">
                    <a href="<?= $this->url->get('user/register') ?>">
                        <span class="fa fa-plus-circle"></span>
                        Register
                    </a>
                </li>
                <li class="<?= $current_page === 'forgotpassword' ? 'active' : '' ?>">
                    <a href="<?= $this->url->get('user/forgotpassword') ?>">
                        <span class="fa fa-meh-o"></span>
                        Password Recovery
                    </a>
                </li>
            </ul>
            <?php endif; ?>
        </nav>
    </div>
</div>